POST http://localhost:8080/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI5NzE3MzUsInN1YiI6ImNmMDcxNDAwLWNmZWEtNGY2ZC1iNjkxLTk0ZTkyZjNkOGZkMyJ9.W9ZA0eDzLJuNoLlHj1KajUKe1d7zFMY5zBOXhyBTnps

{
    "name": "Product 1",
    "price": 100
}

###

GET http://localhost:8080/products/fec6ec34-4940-4016-b32c-5915131f43c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI5NzE3MzUsInN1YiI6ImNmMDcxNDAwLWNmZWEtNGY2ZC1iNjkxLTk0ZTkyZjNkOGZkMyJ9.W9ZA0eDzLJuNoLlHj1KajUKe1d7zFMY5zBOXhyBTnps

###

PUT http://localhost:8080/products/fec6ec34-4940-4016-b32c-5915131f43c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI5NzE3MzUsInN1YiI6ImNmMDcxNDAwLWNmZWEtNGY2ZC1iNjkxLTk0ZTkyZjNkOGZkMyJ9.W9ZA0eDzLJuNoLlHj1KajUKe1d7zFMY5zBOXhyBTnps

{
    "name": "Product 2",
    "price": 100
}

###

DELETE http://localhost:8080/products/fec6ec34-4940-4016-b32c-5915131f43c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI5NzE3MzUsInN1YiI6ImNmMDcxNDAwLWNmZWEtNGY2ZC1iNjkxLTk0ZTkyZjNkOGZkMyJ9.W9ZA0eDzLJuNoLlHj1KajUKe1d7zFMY5zBOXhyBTnps

###
GET http://localhost:8080/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI5NzE3MzUsInN1YiI6ImNmMDcxNDAwLWNmZWEtNGY2ZC1iNjkxLTk0ZTkyZjNkOGZkMyJ9.W9ZA0eDzLJuNoLlHj1KajUKe1d7zFMY5zBOXhyBTnps
